name: Vercel Preview Deployment
env:
  PREVIEW_GOOGLE_APPLICATION_CREDENTIALS_BASE64: ${{ secrets.PREVIEW_GOOGLE_APPLICATION_CREDENTIALS_BASE64 }}
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  push:
    branches:
      - preview
  pull_request:
    branches:
      - preview
jobs:
  Unit-Test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 19.x
      - name: Install Node Dependencies
        run: npm ci
      - name: Running Jest Tests
        run: npm test
  Firebase-Cloud-Functions-Preview-Deployment:
    env:
      GOOGLE_APPLICATION_CREDENTIALS: google-application-credentials.json
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 19.x
      - name: Install Dependencies
        shell: bash
        working-directory: ./functions
        run: |
          npm ci
      - name: Install Firebase CLI
        run: npm install --global firebase-tools
      - name: Prepare Google Application Credentials
        shell: bash
        run: |
          echo "${{ secrets.PREVIEW_GOOGLE_APPLICATION_CREDENTIALS_BASE64 }}" | base64 --decode > "google-application-credentials.json"
      - name: Use Firebase Preview
        shell: bash
        run: |
          firebase use preview --debug
      - name: Deploy Firebase Cloud Functions
        run: firebase deploy --only functions --non-interactive --debug
      - name: Remove credentials file
        if: success() || failure()
        run: |
          rm google-application-credentials.json
  Deploy-Preview:
    needs: Unit-Test
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 19.x
      - name: Install Node Dependencies
        run: npm ci
      - name: Install Cloud Functions Node Dependencies
        run: cd functions && npm ci && cd ..
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }} --archive=tgz