name: Vercel Production Deployment
env:
  PROD_GOOGLE_APPLICATION_CREDENTIALS_BASE64: ${{ secrets.PROD_GOOGLE_APPLICATION_CREDENTIALS_BASE64 }}
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  push:
    branches:
      - main
jobs:
  Unit-Test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 19.x
      - name: Install Node Dependencies
        run: npm ci
      - name: Running Jest Tests
        run: npm test
  Firebase-Cloud-Functions-Production-Deployment:
    env:
      GOOGLE_APPLICATION_CREDENTIALS: google-application-credentials.json
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 19.x
      - name: Install Dependencies
        shell: bash
        working-directory: ./functions
        run: |
          npm ci
      - name: Install Firebase CLI
        run: npm install --global firebase-tools
      - name: Prepare Google Application Credentials
        shell: bash
        run: |
          echo "${{ secrets.PROD_GOOGLE_APPLICATION_CREDENTIALS_BASE64 }}" | base64 --decode > "google-application-credentials.json"
      - name: Use Firebase Production
        shell: bash
        run: |
          firebase use production --debug
      - name: Deploy Firebase Cloud Functions
        run: firebase deploy --only functions --non-interactive --debug
      - name: Remove credentials file
        if: success() || failure()
        run: |
          rm google-application-credentials.json
  Deploy-Production:
    needs: Unit-Test
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 19.x
      - name: Install Node Dependencies
        run: npm ci
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: |
          url="$(vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }} --archive=tgz)"
          vercel alias --token=${{ secrets.VERCEL_TOKEN }} set "$url" taboo-ai.vercel.app