name: Vercel Production Deployment
env:
  PROD_GOOGLE_APPLICATION_CREDENTIALS_BASE64: ${{ secrets.PROD_GOOGLE_APPLICATION_CREDENTIALS_BASE64 }}
on:
  push:
    branches:
      - main
jobs:
  Unit-Test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 19.x
      - name: Install Node Dependencies
        run: npm ci
      - name: Running Jest Tests
        run: npm test
  Firebase-Cloud-Functions-Production-Deployment:
    env:
      GOOGLE_APPLICATION_CREDENTIALS: google-application-credentials.json
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 19.x
      - name: Install Dependencies
        shell: bash
        working-directory: ./functions
        run: |
          npm ci
      - name: Install Firebase CLI
        run: npm install --global firebase-tools
      - name: Prepare Google Application Credentials
        shell: bash
        run: |
          echo "${{ secrets.PROD_GOOGLE_APPLICATION_CREDENTIALS_BASE64 }}" | base64 --decode > "google-application-credentials.json"
      - name: Use Firebase Production
        shell: bash
        run: |
          firebase use production --debug
      - name: Deploy Firebase Cloud Functions
        run: firebase deploy --only functions --non-interactive --debug
      - name: Remove credentials file
        if: success() || failure()
        run: |
          rm google-application-credentials.json