name: Run Tests
on: pull_request
jobs:
  Unit-Test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 19.x
      - name: Install Node Dependencies
        run: npm ci
      - name: Running Jest Tests
        run: npm test